name: Run Notebook

on:
  push:
    branches: [ main ]

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t repro_image .

    - name: Execute notebook
      run: |
        docker run --rm -v ${{ github.workspace }}:/app repro_image \
          conda run -n sc jupyter nbconvert \
          --to notebook \
          --execute \
          --inplace \
          --ExecutePreprocessor.kernel_name=ir \
          --ExecutePreprocessor.allow_errors=True \
          Fig5_R_goanalysis.ipynb

    - name: Upload notebook and data as artifact
      uses: actions/upload-artifact@v4
      with:
        name: executed-notebook
        path: |
          Fig5_R_goanalysis.ipynb
          data/**
